name: "Sidebar"
run-name: Update wiki sidebar

description: "Github Action for creating/updating a customized sidebar for Github wikis."
author: "GeodF"

branding:
  color: "green"
  icon: "package"

inputs:
  menu_title:
    description: "Menu title"
    required: false
  menu_pages:
    description: "Menu pages (1st level). Default: your previous list."
    required: false
  menu_size:
    description: "Size: 1, 2, 3, 4, or 5."
    required: false
  menu_color:
    description: "Color (not implemented)"
    required: false
  menu_footer:
    description: "Menu footer"
    required: false

runs:
  using: "composite"
  steps:
    - name: Starting
      shell: bash
      run: echo "🎉 job triggered by a ${{ github.event_name }} event on ${{ github.repository }}."

    # ref: https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        
    - name: Checkout Wiki
      uses: actions/checkout@v4
      with:
        repository: ${{github.repository}}.wiki

    - name: Update sidebar
      shell: bash
      run: |
        ${GITHUB_ACTION_PATH}/scripts/update_wiki_sidebar.sh \
        --title="${{ inputs.menu_title }}" \
        --footer="${{ inputs.menu_footer }}" \
        --size="${{ inputs.menu_size }}" \
        --color="${{ inputs.menu_color }}" \
        ${{ inputs.menu_pages }} > _Sidebar.md
        
    - name: Debug
      shell: bash
      run: |
        ls
        cat _last_menu_pages
        cat _Sidebar.md


    - name: Commit the updated sidebar
      shell: bash
      run: |
        git config user.name "$(git log -n 1 --pretty=format:%an)"
        git config user.email "$(git log -n 1 --pretty=format:%ae)"
        git add _Sidebar.md _last_menu_pages
        if ! git diff-index --quiet HEAD; then
          git commit -m 'Updated by GeodF/sidebar action.'
          git push
        fi


