name: "Sidebar"
run-name: Update wiki sidebar

description: "Github Action for creating/updating a customized sidebar for Github wikis."
author: "GeodF"

branding:
  color: "green"
  icon: "package"

inputs:
  menu_title:
    description: "Menu title"
    required: false
  size:
    description: "Size"
    required: false
  color:
    description: "Color"
    required: false

runs:
  using: "composite"
  steps:
    - name: Starting
      shell: bash
      run: echo "🎉 job triggered by a ${{ github.event_name }} event on ${{ github.repository }}."

    # ref: https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        
    - name: Checkout Wiki
      uses: actions/checkout@v4
      with:
        repository: ${{github.repository}}.wiki

    - name: Update sidebar
      shell: bash
      run: ${GITHUB_ACTION_PATH}/scripts/update_wiki_sidebar.sh --size=3 > _sidebar.md

    - name: Commit the updated sidebar
      shell: bash
      run: |
        git add _sidebar.md
        git commit -m 'Updated by GeodF/sidebar action.'
        git push


