name: "Sidebar"
run-name: Update wiki sidebar

description: "Create/update a customized sidebar for Github wiki."
author: "GeodF"

branding:
  color: "green"
  icon: "menu"

inputs:
  menu_title:
    description: "Title"
    required: false
  menu_pages:
    description: "Pages (1st level). Default: your previous list."
    required: false
  menu_footer:
    description: "Footer"
    required: false
  menu_opened:
    description: "Opened ?"
    required: false
    type: boolean
  menu_size:
    description: "Size: 1, 2, 3, 4, or 5."
    required: false

runs:
  using: "composite"
  steps:
    - name: Starting
      shell: bash
      run: echo "🎉 job triggered by a ${{ github.event_name }} event on ${{ github.repository }}."

    # ref: https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        
    - name: Checkout Wiki
      id: checkout
      uses: actions/checkout@v4
      with:
        repository: ${{github.repository}}.wiki

    - name: Update sidebar
      id: update_sidebar
      shell: bash
      if: steps.checkout.outcome == 'success'
      run: |
        ${GITHUB_ACTION_PATH}/scripts/update_wiki_sidebar.sh \
        --title="${{ inputs.menu_title }}" \
        --footer="${{ inputs.menu_footer }}" \
        --opened="${{ inputs.menu_opened }}" \
        --size="${{ inputs.menu_size }}" \
        ${{ inputs.menu_pages }} > _Sidebar.md

    - name: Commit the updated sidebar
      shell: bash
      if: steps.update_sidebar.outcome == 'success'
      run: |
        git config user.name "$(git log -n 1 --pretty=format:%an)"
        git config user.email "$(git log -n 1 --pretty=format:%ae)"
        git add _Sidebar.md _last_menu_pages
        if ! git diff-index --quiet HEAD; then
          git commit -m 'Updated by GeodF/sidebar action.'
          git push
        fi


