name: Update Major Version Tag
run-name: ${{ github.actor }} Update major version tag

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  update_major_version_tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get version tag and update major version tag
      shell: bash
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        MAJOR=${VERSION%%.*}      
        git config user.name "$(git log -n 1 --pretty=format:%an)"
        git config user.email "$(git log -n 1 --pretty=format:%ae)"
        git tag -fa "${MAJOR}" -m 'Update major version tag'
        git push origin "${MAJOR}" --force
