name: Update Development Version Tag
run-name: ${{ github.actor }} Update dev version tag

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - main
    paths:
      - 'scripts/**'
  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_dev_version_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Update tag to the last commit
      run: |
        git config user.name "$(git log -n 1 --pretty=format:%an)"
        git config user.email "$(git log -n 1 --pretty=format:%ae)"
        git tag -fa "dev" -m 'Update dev version tag'
        git push origin "dev" --force

